@startuml CreateUser

skinparam boundary {
  backgroundColor DodgerBlue
  borderColor black
}

skinparam control {
  backgroundColor LimeGreen
  borderColor black
}

skinparam entity {
  backgroundColor Orange
  borderColor black
}

actor Actor
boundary AccountView
control AccountController
entity UserRepository
entity UserEntity

Actor -right-> (AccountView) : 1.setUserData()\n2.create(user)
(AccountView) --> (AccountController) : 3.create(user)
(AccountController) --> (UserRepository) : 6.register(user)
(AccountController) --> (UserEntity) : 4.checkIsInSession(user)\n5.checkIfExits(user)
@enduml