@startuml RecoveryPassword

skinparam boundary {
  backgroundColor DodgerBlue
  borderColor black
}

skinparam control {
  backgroundColor LimeGreen
  borderColor black
}

skinparam entity {
  backgroundColor Orange
  borderColor black
}

actor Actor
boundary AccountView
control AccountController
entity UserRepository

Actor -right-> (AccountView) : 1.forgotPassword()\n 2.setMail()
(AccountView) -down-> (AccountController) : 3.forgotPassword(email)
(AccountController) -down-> (UserRepository) : 4.findByEmail(email) \n 5.forgotPassword(User)
@enduml