@startuml SetNewPassword

skinparam boundary {
  backgroundColor DodgerBlue
  borderColor black
}

skinparam control {
  backgroundColor LimeGreen
  borderColor black
}

skinparam entity {
  backgroundColor Orange
  borderColor black
}

actor Actor
boundary AccountView
control AccountController
entity UserRepository
entity UserEntity

Actor -right-> (AccountView) : 1.registerNewPassword(email)\r 2.setPassword()
(AccountView) -down-> (AccountController) : 3.resetPassword(userId, newPassword)
(AccountController) -down-> (UserRepository) : 4.findByEmail(email)\r 6.save(User)
(AccountController) -down-> (UserEntity) : 5.resetPassword(userId, newPassword)
@enduml