@startuml AddCommentToBorrow

skinparam boundary {
  backgroundColor DodgerBlue
  borderColor black
}

skinparam control {
  backgroundColor LimeGreen
  borderColor black
}

skinparam entity {
  backgroundColor Orange
  borderColor black
}

actor Actor
boundary BorrowView
control BorrowController
entity BorrowRepository
entity BorrowEntity

Actor -right-> (BorrowView) : 1.addComment(borrowId, comment)
(BorrowView) --> (BorrowController) : 2.addComment(borrowId, comment)
(BorrowController) -down-> (BorrowEntity) : 3.addComment(comment)
(BorrowController) -down-> (BorrowRepository) : 4.save(borrow)
@enduml