@startuml ShowBorrowDetail

skinparam boundary {
  backgroundColor DodgerBlue
  borderColor black
}

skinparam control {
  backgroundColor LimeGreen
  borderColor black
}

skinparam entity {
  backgroundColor Orange
  borderColor black
}

actor Actor
boundary BorrowView
control BorrowController
entity BorrowRepository

Actor -right-> (BorrowView) : 1.showBorrowDetail(id)
(BorrowView) --> (BorrowController) : 2.getBorrowDetail(id)
(BorrowController) --> (BorrowRepository) : 3.get(id)

@enduml