@startuml ShowUserScore

skinparam boundary {
  backgroundColor DodgerBlue
  borderColor black
}

skinparam control {
  backgroundColor LimeGreen
  borderColor black
}

skinparam entity {
  backgroundColor Orange
  borderColor black
}

actor Actor
boundary BorrowView
control BorrowController
entity BorrowRepository

Actor -right-> (BorrowView) : 1.viewScore()
(BorrowView) --> (BorrowController) : 2.getOwnerDetail(borrowId)
(BorrowController) --> (BorrowRepository) : 3.GetAllLenderFromBorrow(borrowId)

@enduml